### ISSUE TITLE
v5 Roadmap

### ISSUE THREAD

**Issue by Moon-0xff** [Moon-0xff/gnome-mpris-label#14]
- [x] Update a few option descriptions
- [x] Change default value of `show-icon` to `true`
- [x] Update extension screenshot (preferably high resolution)
- [x] Decide whether to keep the chromium icon workaround, discard it for the time being, or create a better one
- [x] Implement an option to choose the icon placement (left or right)
- [x] Test the extension thoroughly

Then finally:
- [x] Submit it to ego
- [x] Create a `stable` branch
- [x] Merge #10

**Comment by Moon-0xff** [comment]
@Batwam can you upload the screenshot? Snapcraft is down

**Comment by Moon-0xff** [comment]
All done. I'm going to close this when the reviewing process finishes.

**Comment by Moon-0xff** [comment]
Got rejected twice so the assigned version is number 7. Whatever.
