### ISSUE TITLE
Todo List - Contributions needed

### ISSUE THREAD

**Issue by Batwam** [Moon-0xff/gnome-mpris-label#4]
It's me again!

## Features list for discussion (original list):
- [x] Add an option to include application icons alongside the label (See #5)
- [x] Add a user definable filter list for mpris sources (See #20) - included in v11
- [x] Add menu to select active player by a dropdown menu (See #23)
- [x] Add an option to pause a player by clicking the label (The original item was small in scope because of limitations(776ed060a51db3d8efc81e607f87f8f581a6e183), later widened and added in ce3dc073735db7543970059c2080b0d3cee07592, see #26)
- [x] Make this extension refresh asynchronously (See #7)

My thoughts:
1. Interesting idea, I wonder if there is an automated way to locate/load these icons in gjs. It would be possible to include icon for the usual apps (rhythmbox, spotify, firefox, chromium,...) which would probably easier but I'm not sure if copyrights would allow it and there is a risk the icon shipped may not match the one used in the distro... there may be some content in the [Vitals](https://github.com/corecoding/Vitals) or [runcat](https://github.com/win0err/gnome-runcat) github repo which could be reused to load icons next to the text as they both have that.
2. Could work. Alternatively, a drop down (or equivalent) with common apps might work too.
3. In terms of implementation, there may be some code to be taken from the Vitals extension as it allows to chose content based on a menu activated when clicking the extension: [https://github.com/corecoding/Vitals](https://github.com/corecoding/Vitals)
4. it might get confusing if clicking shows the menu in some cases but pauses in other cases? Including these controls within a menu might be better, something similar to this other discontinued [mpris extension](https://extensions.gnome.org/extension/54/mpris-player-control/)
5. I agree that the current implementation which continuously updates is somewhat suboptimal but I don't know if this is even possibly. If it was, I wonder how much this would really save in terms of resource.

- [x] **Bonus Extra:**
Update extension name/description to make what the extension does more obvious and therefore more popular. I'm not sure how I found it initially but not everyone would be familiar with mpris. A lot of the other mpris extensions are not compatible with Gnome 43 so the market is up for grabs :-) There is a user review along the same lines:
![image](https://user-images.githubusercontent.com/56710655/203795360-55d5ceaa-3f2f-4831-b9ca-ca90afd8989c.png)

## Features list for discussion (later additions):
- [x] Add tooltips in Settings panel to clarify the purpose of the various settings. (See #22) - included in v11
- [ ] Add (regex) text filtering for labels (See #25)
- [x] Adjust volume with mouse scroll (See #30)

**Comment by Moon-0xff** [comment]
I wanted to only discuss what should be added to the next release, but sure, let's discuss this list.

### A general response to your thoughts
The *objective* of this extension (as the description says) is to work with any mpris compatible source. We don't want to restrict certain features to only a limited amount of players, and we don't have to! The freedesktop specifications (and others) are largely respected. 

### 1. Icons alongside the label
sp-tray looks great with the spotify icon and I'm jealous!

How to achieve this? I don't know but GNOME does it already, so it's probably just a matter of copying the code. If that fails then I'm pretty sure there's a standard way of accessing icons, as icons rarely if ever goes missing, regardless of DE/WM or even container (flatpak,snap,appimages).

### 2. Filter list

We **need** this feature, specially with the auto-switch option as we discussed previously.

Implementing it isn't a problem.
The challenge will be to accommodate it to the settings UI, probably will need a complete UI overhaul, and I'm not proficient with GTK at all!

### 3. Change player with a dropdown menu

Cycling players by clicking the label it's a bit awkward. I wanted to do this in the first place, but again, GTK.

Gnome maintains an example of how to do dropdown menus in extensions, the challenge here will be probably to maintain compatibility with GNOME 3.3x

### 4. Clicking the label to pause

Might get confusing? Probably, I was thinking of this as a optional feature (turned off by default). I find it useful!

Regarding the extension you linked, i don't want to replicate it.
Other extensions do this already, and they suffer a lot when GNOME changes version, i don't want to deal with that!

#### 5. This extension as async

It's a matter of doing it right
The mpris specification and gjs.guide point to accesing DBus asynchronously

But also it's about resources, we are using a lot more cpu cycles than we need!

### The bonus

It's a good idea, the extension name and description it's far too technical, but i don't want to give the impression that this extension only works for music.

This extension originally was named mpris-music-label. I didn't like this name as really the media could be anything!

**Comment by Batwam** [comment]
Draft code for item 1 included in Pull Request #5 . Hopefully you won't be jealous for long!

**Comment by Moon-0xff** [comment]
#5 was merged. Once again. Thanks @Batwam for all your contributions.

**Comment by Moon-0xff** [comment]
Last changes to this list:
Removed number 5 because is "in progress"

**Comment by Batwam** [comment]
one thing to note also is that when available, mpris includes a path to the album icon as part of the metadata string. This means that rather than loading the app icon, we could in theory load the album picture instead. For apps like shortwave with radio station logo instead of the app logo for instance, that could be quite neat. Same thing if we were to show the album picture rather than the Spotify icon also I guess, it kind of depends on the bar size/resolution as it could be quite small. 
![image](https://user-images.githubusercontent.com/56710655/207370212-33b6a666-f1e3-4027-aac2-359540d674cc.png)

When the icon is stored locally like with Rhythmbox, it will provide a local file:/// path.

**Comment by Moon-0xff** [comment]
Sounds real neat specially with shortwave, but we get less than 32px in a 1920x1080 screen, album covers are far too detailed to translate well into such a small amount of pixels.

As a "general" option i don't think is of too much use, as a "per-application" option sounds good, but we will need to implement "per-application options" first.

**Comment by Batwam** [comment]
for info, I have tested Opera/Brave/Vivaldi in a VM. As expected, it won't load the icons but the following code works (`Brave` had to be capitalised to work for some reason), the problem being obviously that since it's not searching through running apps, it will pick up the icon from the first app which is installed, regardless of whether it's the correct one or not... which is why I have loaded them in order of popularity:
`	if (suspectAppName == "chromium" && matchedEntries.length === 0)
		matchedEntries = Gio.DesktopAppInfo.search("Opera")

	if (suspectAppName == "chromium" && matchedEntries.length === 0)
		matchedEntries = Gio.DesktopAppInfo.search("Brave")

	if (suspectAppName == "chromium" && matchedEntries.length === 0)
		matchedEntries = Gio.DesktopAppInfo.search("Vivaldi")`

these were installed using debs (Opera/Vivaldi) when no flatpak was available. Brave was flatpak. I tried the snaps but for some reaons there is an issue with appArmor and they can't seem to be able to get access to mpris so the extension doesn't work for snap versions of these browsers (works for firefox though...).

**Comment by Moon-0xff** [comment]
This conversation belongs to #8 but whatever.
As previously mentioned, there's a way of getting desktop entries from running apps. This doesn't solve our problem directly but surely a solution can be coded from it.
Regarding the problems with D-Bus access that's not so unexpected, I'm pretty sure a lot of packagers will perceive it as an unnecessary security risk.

**Comment by Batwam** [comment]
By the way, I noticed that the color-picker extension has implemented different actions for right Vs left click on the extension icon. I thought that it's interesting as the other extensions I checked all handled left and right clicks the same way and I assumed that it was a limitation in gjs. Apparently not. 

This opens up some additional opportunities for right click pop-up manually select player or select "Automatic Switch" Vs Left click track info, track controls or things like that: https://github.com/tuberry/color-picker

**Comment by Moon-0xff** [comment]
I thought the same. Then sure, we can use a button for the player selection and the other for "Additional actions".
But how color-picker achieves that exactly?

**Comment by Batwam** [comment]
I haven't spent too much time on it but I suspect that it lies within this part of the `extension.js` code so it might be catching the click and run a different action if it's a left click:
![image](https://user-images.githubusercontent.com/56710655/208335647-cf332419-2479-4c29-9e73-a666f2b4125a.png)

This second part seems to command differentiated action when picking colours with left=select, middle=menu, right=escape
![image](https://user-images.githubusercontent.com/56710655/208335307-7306c289-3bab-471f-bc39-1718d630d5ae.png)

**Comment by Moon-0xff** [comment]
The recent changes I made to `prefs.js` can accommodate a filter list (we only need to add another page to `prefsWidget`)

However they are two problems:
1. Under GNOME 4x the window looks wrong and is not correctly aligned at startup (in GNOME 3.3x looks and behaves very nice)
2. I'm not sure how to implement the interface for the filter list in GTK.

**Comment by Batwam** [comment]
Neat menu! yeah, I just noticed that you pushed a new commit for #1. It looks fine for me.

Wouldn't the interface for filter be a simple text field where the user would include his regex expressions, possibly delimited with commas?

**Comment by Moon-0xff** [comment]
I was thinking in making some sort of dynamic list with widgets, easier to use but harder to implement.

Last update was less than a week ago so i don't think the changes justify an update yet.

**Comment by Moon-0xff** [comment]
I added the filters list page using your proposed interface. I don't think usability suffers at all.  
The branch name is filter-list

**Comment by Batwam** [comment]
I had a look at the white list implementation and still can't think of a case where it could prove useful. The only time it would do something would be if someone included the same source in blacklist and whitelist and even then, it would be questionable whether the blacklist or whitelist should take priority. 

If we had a full on regex syntax with wildcards then there could have been a slim use case but since we don't (currently) and it would probably be over the top for this application (there aren't that many mpris sources the user is likely to have on his system), I still think that we are over complicating the interface with a whitelist. Any thoughts?

**Comment by Moon-0xff** [comment]
As I said, the whitelist isn't very useful on it's own, so i added a new option to make it useful, the new option treats all non-whitelisted sources as blacklisted, this is useful if you want to use this extension with just one player.

Overall the whitelist and this new option just saves a few annoyances and a bit of user input, so if the whitelist proves to be problematic I'm not against removing it.

**Comment by Batwam** [comment]
Oh, I see. Would it make sense then to instead have a drop down where the user decides if he want a blacklist or a white list, with the text field underneath which will be treat accordingly depending on the drop down value?

I'm also thinking, we both know what each option does but some would probably be rather obscure to a new user. Is there a way to add some sort of ControlTip extended description which would appear when the user puts its mouse over the item?

**Comment by Moon-0xff** [comment]
Yes, i don't think using both whitelist and blacklist at the same time is useful at all, and this change could simplify the code a bit, although i don't see how we can present it in a clear way, with a drop-down one value (or both) will be obscured. 

> ToolTip extended description which would appear when the user puts its mouse over the item?

I searched for something like that in the documentation with no luck https://gjs-docs.gnome.org/gtk30~3.0/

**Comment by Batwam** [comment]
yeah, I was somewhat hopefuly reading this page but nothing seems to work. I had a look at some of the other extensions and couldn't find examples of tooltip. The only thing I found are descriptions like this:
![image](https://user-images.githubusercontent.com/56710655/214324800-a54633c0-6db5-4425-af3e-048a7eaf4eee.png)

When it comes to the filters themselves, if we are concerned that the terms blacklist/whitelist may no be self-explanatory, we could quite easily just add some text at the top of bottom to explain what each does.

**Comment by Moon-0xff** [comment]
I found `Gtk.Widget.set_tooltip_text` and does exactly what we want.

Add this line to the `addLabel` function in `prefs.js`:
`thisLabel.set_tooltip_text('Example Text');`
and point the mouse over any label

**Comment by Batwam** [comment]
Nice, I saw the command and where it should have gone but I was a bit confused as VS Code didn't seem to propose it...

See #19 with tooltip implementation and some tooltips populated (rest left as `undefined` with no tooltip generated).

**Comment by Moon-0xff** [comment]
For the bonus, have you read the current description?

The day i rewrote the description the extension received two more comments on EGO so it works. Although the current description is a "condensed version" of the original rewrite.

**Comment by Batwam** [comment]
Nice once, I didn't notice actually. Do you want another screenshot to show it working with a different player in the bottom panel? Or maybe include "also compatible with Dash to panel for anyone wondering?

**Comment by Moon-0xff** [comment]
Submitted the new version to ego (hopefully isn't rejected twice again)

**Comment by Batwam** [comment]
Excellent. That's action 2&3 done then. Anything else to be done on those? I wasn't sure why the ChangeLog was changed from "v11" to "upcoming"

**Comment by Moon-0xff** [comment]
because the version is assigned by ego, and might be higher if the first upload is rejected

**Comment by Batwam** [comment]
Ah, that's why we jumped from v7 to v10, I understand now! Did the resubmissions require code change? Do they tell you why they reject?

**Comment by Moon-0xff** [comment]
You can see the ego reviews for the extension in [this link](https://extensions.gnome.org/review/38216)  
**Warning:** some of them are really silly

For a quick rundown:
v2: Forgot to delete the .git folder
v5: Forgot to remove the install script
v6: The time i submitted this overlapped with the review time so i didn't read v5 review
v8 and v9: global scope issues

**Comment by Batwam** [comment]
In a way, I'm positively impressed they are reviewing it thoroughly. They also provide feedback with links with references which is nice of them. Just learnt than the Lang module is depreciated which is good to know as I was about to use it...

**Comment by Batwam** [comment]
Thanks for updating the version to v12, otherwise the extension keeps getting updated automatically in the background by gnome and it overwrites the test versions if they have a lower rev.

**Comment by Moon-0xff** [comment]
I'm thinking of embedding the controls to the label this way:

- Long press to pause
- Double click to next
- Click, short pause, click to previous

This (maybe) could be implemented by just watching the click event and a timer.

I already added the control methods and started a branch: `controls`

**Comment by Moon-0xff** [comment]
I forgot about the Clutter button events, if we can make them work then we can do a better layout, I'm thinking of:

* Left double click to next
* Right double click to prev
* Middle click to pause
* Single left click to switch players
* And maybe, single right click for "Additional actions"

All of this, of course, customizable through settings

**Comment by Batwam** [comment]
Yeah, I'm just not convinced "double click" is an event type: https://lazka.github.io/pgi-docs/Clutter-0/enums.html#Clutter.EventType

I certainly haven't seen it implemented on any of the extensions I have installed. Do you have any early indication it might we possible?

Without it, the options are going to be limited to left/middle/right.

The alternative would to throw these controls into a menu like everyone else. I'm personally not bothered as I have keyboard shortcuts but there is no other way and we are ok to included a menu for these controls, we can always make that section if the menu optional.

**Comment by Moon-0xff** [comment]
I can definitely imagine how a double click could be detected:

* Record the time when a 'clicked' event is triggered
* If the time between this 'clicked' event and the last one is shorter than `THRESHOLD` then:
**It's a double click!**

**Comment by Moon-0xff** [comment]
I certainly would prefer them as a mouse layout instead of a menu. Also, i haven't had any luck adding a menu to the extension, so i would prefer a solution that doesn't involve them.

**Comment by Batwam** [comment]
I did have a go at the menu thing and am making some progress although it still needs some of the building blocks. 

Have a look at my `menu_test` branch. I haven't pushed it as it's not functional but I have a dynamic menu (which doesn't do anything currently but shows what it could look like this:
![image](https://user-images.githubusercontent.com/56710655/215239007-be86a633-76a9-4629-92d3-46d3432684de.png)

Let me know if this is something you'd like to explore. I personnall think that it looks quite neat to address item 4.

**Comment by Moon-0xff** [comment]
As you mentioned it, this could limit what we can do for the controls. I don't perceive this as a bad trade-off.

Embedding controls to the label is an afterthought, a neat and useful feature, but the idea of selecting the source with a menu is the original idea for the extension.

I share your ideas about the menu, however i think you are doing too much at the same time, maybe try to get the "bare minimum" working first, a working selection and the indicator for the current one. That alone would be release worthy (but we pushed an update very recently so that wouldn't be the case).

This is great! Keep up the good work! and submit a PR if you get the "bare minimum" working, i would add it to `main` right away.

**Comment by HubKing** [comment]
How about scrolling mouse over the song title controls the audio volume? I know that there already is an extension that controls volume by scrolling, so it must be technically possible. The problem of that existing extension is that the mouse scroll action applies to the entire Top Bar, which causes problems with other extensions that take scroll input.

**Comment by Batwam** [comment]
That sounds pretty odd if the scroll impacts other extensions. Do you have a link to that extension?

With the upcoming popmenu for player selection, right click will be taken but there could certainly be additional capabilities which could be considered **if** we are able to implement a method to distinguish between left/middle/scroll. We know it is possible on the color-picker extension but I haven't seen other extensions doing it and we haven't implemented this yet.

Once implemented, doing mpris calls like pre/next/play/pause/volume_up/volume_down should be relatively straightforward but that would be another thing to implement as we are currently only reading data.

**Comment by HubKing** [comment]
> That sounds pretty odd if the scroll impacts other extensions. Do you have a link to that extension?

https://github.com/trflynn89/gnome-shell-volume-scroller

By "affecting", I meant that there are other extensions who do something else when the users scrolls the wheel above that extension's entry on the TopBar, and since this extension affects the whole TopBar, when I scrolled the wheel over the extension's entry, it did both (doing that extension's job and changing the volume).

**Comment by Batwam** [comment]
ok, I had a look and, if I understand correctly, the whole point of that extension is for the user to be able to change the volume by scrolling anywhere along the menu so the behaviour seems to make sense. Do you have a link to one of the extensions which takes user scroll as an input? that would be useful.

One thing we could potentially look into is, rather than changing the overall system volume like the extension you showed, it should be possible to only affect the volume of the individual mpris source selected. Somewhat similar in function to [this extension](https://extensions.gnome.org/extension/3499/application-volume-mixer/), but without the menu. If people want to change the system volume, that can already scroll over the sound icon so no need to duplicate that.

**Comment by Batwam** [comment]
ok, I've managed to implement the volume control with wheel scroll by grabbing `'scroll-event'`. It changes the volume of the active mpris source. See branch/pull request above. Any comment on the implementation should be made directly in #26.

@Moon-0xff I'll wait for your feedback before going further. We should finish implementing the filters we have been working on before considering this feature but shows that it can be done. I know that you are busy so no rush ;-)

**Comment by HubKing** [comment]
>  If people want to change the system volume, they can already scroll over the sound icon so no need to duplicate that.

No, we can't, if by "sound icon" you mean the thing on the right-most of the TopBar where the Wi-Fi icon and battery icon is. In fact, I have been (internally) complaining about this. I have been thinking that I may need to create an extension that shows the system audio volume and the monitor brightness and I could change them (volume and brightness) )by scrolling over it.

**Comment by Batwam** [comment]
Yeah, it's arguably a bit small but you can definitely change the system volume by scrolling over the speaker icon. 

Have you tried the `controls_test` branch? Does it do what you want?

**Comment by Moon-0xff** [comment]
Hello @Batwam I'm indeed quite busy to review the code.

The idea sounds good, and by the screenshot i judge it looks good too.  

I think of two possible problems:
* Some players might react wrongly to the signal
* Some players don't implement the method

There's methods in mpris to know the players capabilities, that and by introspecting the proxy (with `Object.keys`) we can probably know if the player will react correctly (or not) to the signal.

Maybe i'm wrong but either way i would prefer to show a graphical indication that the volume control doesn't work with the player (if we can confidently know). I have no idea how that could be achieved.

Option wise, I'm thinking of a combobox with these options (if we can know if players react or not to the signal):
* global
* application
* application and fallback to global
* off

I can't help with the code or test it for now, but i will keep an eye on the comments and commit messages.

Let me know how it goes!

**Comment by Moon-0xff** [comment]
I trust your senses and if you think it's ready to merge i will do it.

Also, i tried to implement the popup menu as an option and failed.

**Comment by Batwam** [comment]
ok, I have implemented an option for Source/Global/Off. It's working except for Chrome for active source control which returns values but doesn't actually affect the app volume...

See #26  for details.
